// Code generated by "stringer -type Direction direction.go"; DO NOT EDIT.

package cible

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DirectionUnknown-0]
	_ = x[Forward-1]
	_ = x[Backward-2]
	_ = x[Left-3]
	_ = x[Right-4]
}

const _Direction_name = "DirectionUnknownForwardBackwardLeftRight"

var _Direction_index = [...]uint8{0, 16, 23, 31, 35, 40}

func (i Direction) String() string {
	if i < 0 || i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
